# This workflow builds and deploys the 'latest' documentation when code is pushed to main.

name: Build and Deploy Latest Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python with uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
            uv pip install -r requirements-docs.txt
            uv pip install requests packaging setuptools
            sudo apt-get install graphviz

      - name: Build documentation for all packages
        run: |
          while IFS= read -r line || [[ -n "$line" ]]; do
            # Trim leading/trailing whitespace and skip comments/empty lines
            line=$(echo "$line" | xargs)
            [[ "$line" =~ ^# ]] || [[ -z "$line" ]] && continue
            
            # Find the last comma to split package spec from version
            # This handles packages with extras like: iqm-pulla[qiskit,qir],10.1.0
            last_comma_pos=${line%,*}
            if [ "$last_comma_pos" = "$line" ]; then
              # No comma found, use entire line as package spec
              package_spec="$line"
            else
              # Extract package spec (everything before the last comma)
              package_spec="$last_comma_pos"
            fi
            
            # Extract the base name (e.g., 'iqm-client' from 'iqm-client[extras]')
            base_name=${package_spec%%\[*}
            
            echo "Queueing docs build for package: $base_name (latest)"
            bash build-docs.sh "$base_name" "latest" "$package_spec"
          done < packages.txt

      - name: Generate landing page
        run: python generate_index.py _site

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site
          clean: false
